### ISSUE TITLE
Add option for additional channel in RQ processing

### ISSUE THREAD

**Issue by cwfink** [berkeleycdms/RQpy#6]
Need to add option for arbitrary number of channels, or at least 4, in RQ processing. This also needs to be able to read events from multiple detectors, or a single detector in HV mode depending on how data is taken.

**Comment by slwatkins** [comment]
Reading events from multiple detectors has been added as a part of pull request #8. Also, processing an arbitrary number of channels in has bee supported as of commit 8cfc2eda59c4b58f330db5b198fb9c19fae4dd34.
